version: '2'

services:
  influxdb:
    image: 1.8.10-alpine
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - influxdb
    ports:
      - '3000:3000'

volumes:
  influxdb-storage: